baseurl: https://TheCellarRoom.github.io/posts/
future: true
lsi: true
highlighter: pygments
paginate: 5
markdown: rdiscount
timezone: Europe/London
source:      .
destination: ./_site
layouts:     ./_layouts
includes:     ./_includes
disqus_shortname: thecellarroom
permalink: :year/:month/:day/:title

## Variables
title : The Cellar Room
description : Service Announcements, Status Updates and Cool Stuff.
url : https://TheCellarRoom.github.io
tagline : The Cellar Room
author :
  name : TheCellarRoom
  github : TheCellarRoom
  twitter : TheCellarRoom
